language: perl

env:
  - OBERTH_TEST_REPO: https://github.com/project-renard/curie.git


matrix:
  include:
    - os: linux
      sudo: required
      services: docker
    - os: osx

before_install:
  - . ./script/ci/travis-oberth.sh
  - travis-oberth before-install

install: travis-oberth install
script:  travis-oberth script
