language: perl

env:
  - ORBITAL_TEST_REPO: https://github.com/project-renard/curie.git


matrix:
  include:
    - os: linux
      sudo: required
      services: docker
    - os: osx

before_install:
  - . ./script/ci/travis-orbital.sh
  - travis-orbital before-install

install: travis-orbital install
script:  travis-orbital script
