language: perl

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
    - os: osx

before_install: ./maint/travis-ci/before-install

install: true

script: ./maint/travis-ci/script
