version: 1.0.{build}

environment:
  matrix:
  - OBERTH_TEST_REPO: https://github.com/project-renard/curie.git
    OBERTH_TEST_REPO_BRANCH: master

cache:
  # cache local::lib
  - C:\msys64\mingw64\lib\perl5\site_perl -> appveyor.yml
  - C:\msys64\mingw64\bin\site_perl -> appveyor.yml
  - C:\msys64\home\%Username%\perl5 -> appveyor.yml
  - maint/cpanfile-git-log -> appveyor.yml
  # cache for devops helper.pl
  - C:\Perl\site -> appveyor.yml

install:
  - ps: . script\ci\appveyor-oberth.ps1
  - ps: appveyor-oberth install

build_script:
  - ps: appveyor-oberth build-script
test_script:
  - ps: appveyor-oberth test-script
  - ps: 7z a $Env:APPVEYOR_BUILD_FOLDER\bootstrap.zip $Env:APPVEYOR_BUILD_FOLDER\extlib
  - ps: 7z a $Env:APPVEYOR_BUILD_FOLDER\build.zip     $Env:OBERTH_TEST_DIR $Env:OBERTH_TEST_DIR\..\local

artifacts:
  - path: bootstrap.zip
    name: bootstrap
  - path: build.zip
    name: build
