version: 1.0.{build}

environment:
  matrix:
  - ORBITAL_TEST_REPO: https://github.com/project-renard/curie.git
    ORBITAL_TEST_REPO_BRANCH: master

cache:
  # cache local::lib
  - C:\msys64\mingw64\lib\perl5\site_perl -> appveyor.yml
  - C:\msys64\mingw64\bin\site_perl -> appveyor.yml
  - C:\msys64\home\%Username%\perl5 -> appveyor.yml
  - maint/cpanfile-git-log -> appveyor.yml
  # cache for devops helper.pl
  - C:\Perl\site -> appveyor.yml

install:
  - ps: . script\ci\appveyor-orbital.ps1
  - ps: appveyor-orbital install

build_script:
  - ps: appveyor-orbital build-script
test_script:
  - ps: appveyor-orbital test-script
